name: Create Tag

on:
  repository_dispatch:
    types: [ version-changed ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ç¡®ä¿æœ‰é€‚å½“çš„æƒé™

      - name: Create new tag
        run: |
          # é…ç½® Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # è·å–æ–°ç‰ˆæœ¬å·
          NEW_VERSION=${{ github.event.client_payload.version }}
          echo "Creating new tag $NEW_VERSION"
          
          # åˆ›å»ºæ–°æ ‡ç­¾å¹¶é™„åŠ æ¶ˆæ¯
          git tag $NEW_VERSION -m "ğŸ”–-ã€Release version $NEW_VERSIONã€‘"
          if [[ $? -ne 0 ]]; then
            echo "Failed to create tag $NEW_VERSION"
            exit 1
          fi
          
          # æ¨é€æ–°æ ‡ç­¾
          git push origin $NEW_VERSION
          if [[ $? -ne 0 ]]; then
            echo "Failed to push tag $NEW_VERSION"
            exit 1
          fi
          
          echo "Successfully created and pushed tag $NEW_VERSION"
